Make map codecs more resistant to erroring entries. Fixes MC-197860
Mojang/DataFixerUpper pull request #55
Opened 2020-12-01 15:17 UTC by alcatrazEscapee

This is a really simple change that I believe fixes MC-197860. More details are in the issue there, but the root of the problem is the `UnboundedMapCodec`'s behavior in the case of erroring entries. Previously, this (along with any other `BaseMapCodec` implementor) would discard all valid entries after an error, while only actually reporting actual erroring entries.

This PR moves the collection of read results outside the check for the data result in the accumulator, such that all valid entries will get added to the immutable map builder, while keeping intact the behavior of the `apply2stable` on the actual success or failure of the result in question.

2020-12-02 00:02 UTC, 50ap5ud5 approved these changes
Looks good. I can confirm this change does indeed fix MC-19786.

I will link some of my findings made for the Forge version fix:
- Minecraft already forces player to overworld if dimension is missing
- PR preserves vanilla dimensions
- PR also preserves working modded dimensions

More information about the testing process and related files:
https://drive.google.com/file/d/1TNqRLxnF9YVujFEvU3STZPzDwUuTUo0-/view?usp=drivesdk

2021-01-16 17:18 UTC, TelepathicGrunt approved these changes

2021-01-16 17:41 UTC, Pepe20129 approved these changes

2021-01-17 00:11 UTC, Ioxom approved these changes

2021-01-30 18:44 UTC, liach requested changes
You should only override this method in `UnboundedMapCodec`. This one imo would break the behavior of simple map codec and make it return incomplete maps for pojo en/decoding.

2021-03-19 19:55 UTC, hYdos approved these changes

2021-05-14 18:04 UTC, proudmuslim-dev approved these changes

2021-12-20 15:29 UTC, MelanX approved these changes

2023-05-09 15:18 UTC, FoggierTiger535 commented
I have this issue on my singleplayer world, would love to get my nether and end dimensions avaliable again, how do I use this fix? I'm not good with code so this is probably really simple and im just dumb :D

2023-05-10 02:57 UTC, M4ximumPizza approved these changes

2024-03-20 14:17 UTC, alcatrazEscapee commented
Thank you!

2024-03-20 14:17 UTC, closed without merging