[CVE-2021-44228]: Update Log4J to resolve security issues
Mojang/DataFixerUpper pull request #59
Opened 2021-12-10 16:45 UTC by Gamebuster19901

Without this, downstream projects that depend on DataFixerUpper may become vulnerable if they don't explicitly specify which log4j version to use.

2021-12-16 09:09 UTC, slicedlime requested changes
Should be 2.16.0 at this point.

2021-12-16 09:25 UTC, boq commented
We will probably switch to SLF4J (at least for libraries), so this PR might not be needed

2021-12-16 21:55 UTC, Gamebuster19901 commented
Okay, feel free to close if you merge #60

2022-01-19 16:25 UTC, Gamebuster19901 commented
Superseded by #60

2022-01-19 16:25 UTC, closed without merging